#created on: 26/01/2011
package nz.co.ecngroup.helloworld;

#list any import classes here.
import nz.co.ecngroup.droolstest.fact.Applicant;
import nz.co.ecngroup.droolstest.helper.Club;
import nz.co.ecngroup.droolstest.helper.Car;
import nz.co.ecngroup.droolstest.helper.Color;

#declare any global variables here

global nz.co.ecngroup.service.DbService dbService;


rule "Hello 1"
	ruleflow-group "hello world group 1"	
	lock-on-active 
	when
		$a : Applicant(age == 0);
	then 
		System.out.println("hello 1 rule 1111111");
		modify($a) {
			setAge( 30 )
		}
		
		//retract($a);
		
end


